import { Facility, FacilitySector, FacilityType } from "../facility.js";
import { Cell } from "../../map/cell.js";
import { Vector2 } from "../../data_structures/vector.js";

/**
 * Abstract base class representing commercial facilities and their components
 */
export abstract class CommercialFacility extends Facility {
    /**
     * Sector of the facility (is commercial!!)
     */
    protected static readonly _FACILITY_SECTOR = FacilitySector.COMMERCIAL;

    /**
     * Base tax revenue generated by the facility
     */
    protected static readonly _BASE_TAX_REVENUE : number;

    /**
     * Base maintenance cost of the facility
     */
    protected static readonly _BASE_MAINTENANCE_COST : number;

    /**
     * Radius used to detect nearby residential facilities
     */
    protected static readonly _RESIDENTIAL_FACILITY_RADIUS : number = 6;

    public facilityCheck(coordinates: Vector2): number {
        let distanceToNearestResidence: number = Infinity;
        //If not within rad of 6
        this.GAME.MAP.BFS(
            coordinates,
            this.GAME.MAP.width + this.GAME.MAP.height,
            (coords: Vector2): boolean => {
                const DISTANCE: number = Math.abs(coords.x - coordinates.x) + Math.abs(coords.y - coordinates.y);
                const CELL: Cell = this.GAME.MAP.getCell(coords);
                if (
                    CELL.facilitySector == FacilitySector.RESIDENTIAL &&
                    DISTANCE < distanceToNearestResidence
                ) {
                    distanceToNearestResidence = DISTANCE;
                }
                return false;
            }
        )
        return distanceToNearestResidence;
    }

    public updateRevenueAndCost(coordinates: Vector2): void {
        const DISTANCE: number = this.facilityCheck(coordinates);

        if (DISTANCE == Infinity) {
            this._taxRevenue = 0;
            this._maintenanceCost = 0;
        } else if (DISTANCE > 6) {
            this._taxRevenue = 6 / DISTANCE * (this.constructor as typeof CommercialFacility)._BASE_TAX_REVENUE;
            this._maintenanceCost = 6 / DISTANCE * (this.constructor as typeof CommercialFacility)._BASE_MAINTENANCE_COST;
        } else {
            this._taxRevenue = (this.constructor as typeof CommercialFacility)._BASE_TAX_REVENUE;
            this._maintenanceCost = (this.constructor as typeof CommercialFacility)._BASE_MAINTENANCE_COST;
        }
    }
}


/**
 * Represents a Store facility, a specific type of commercial facility
 * Defines build cost, maintenance, pollution, tax revenue, and static metadata
 */
export class Store extends CommercialFacility {
    /**
     * The facility's type (it's store ofc)
     */
    protected static readonly _FACILITY_TYPE = FacilityType.STORE;

    /**
     * The name of the facility, really.
     */
    protected static readonly _NAME = "Store";

    /**
     * The cost to build the store
     */
    protected static readonly _BUILD_COST: number = 2000000;

    /**
     * The current maintenance cost of the store
     */
    protected _maintenanceCost : number = 50000;

    /**
     * The power consumption of the store
     */
    protected static readonly _POWER_COST: number = 5;

    /**
     * The pollution generated by the store
     */
    protected _pollution : number = 500;	

    /**
     * The tax revenue generated by the store
     */
    protected _taxRevenue : number = 200000;

    /**
     * The base tax revenue for the store
     */
    protected static readonly _BASE_TAX_REVENUE : number = 200000;

    /**
     * The base maintenance cost for the store
     */
    protected static readonly _BASE_MAINTENANCE_COST : number = 50000;
}

/**
 * Represents a Restaurant facility and its respective components
 */
export class Restaurant extends CommercialFacility {
    /**
     * The facility type
     */
    protected static readonly _FACILITY_TYPE = FacilityType.RESTAURANT;

    /**
     * The name of the facility
     */
    protected static readonly _NAME = "Restaurant";

    /**
     * The cost to build the restaurant
     */
    protected static readonly _BUILD_COST: number = 250000;

    /**
     * The maintenance cost of the restaurant
     */
    protected _maintenanceCost : number = 5000;

    /**
     * The power consumption of the restaurant
     */
    protected static readonly _POWER_COST: number = 5;

    /**
     * The pollution generated by the restaurant
     */
    protected _pollution : number = 300;	

    /**
     * The tax revenue produced by the restaurant
     */
    protected _taxRevenue : number = 10000;

    /**
     * The base tax revenue generated by the restaurant
     */
    protected static readonly _BASE_TAX_REVENUE : number = 10000;

    /**
     * The base maintenance cost for the restaurant
     */
    protected static readonly _BASE_MAINTENANCE_COST : number = 5000;
}

/**
 * Represents an Office facility and its respective components
 */
export class Office extends CommercialFacility {
    /**
     * The specific facility type 
     */
    protected static readonly _FACILITY_TYPE = FacilityType.OFFICE;

    /**
     * The name of the facility
     */
    protected static readonly _NAME = "Office";
    
    /**
     * The cost to build the office
     */
    protected static readonly _BUILD_COST: number = 3000000;

    /**
     * The current maintenance cost
     */
    protected _maintenanceCost : number = 5000;

    /**
     * The power consumption of the office
     */
    protected static readonly _POWER_COST: number = 15;

    /**
     * The pollution generated by the office
     */
    protected _pollution : number = 800;	

    /**
     * The tax revenue produced by the office
     */
    protected _taxRevenue : number = 20000;
    
    /**
     * The base tax revenue for the office
     */
    protected static readonly _BASE_TAX_REVENUE : number = 20000;

    /**
     * The base maintenance cost for the office
     */
    protected static readonly _BASE_MAINTENANCE_COST : number = 5000;
}