import { Facility, FacilitySector, FacilityType } from "../facility.js";
import { Vector2 } from "../../data_structures/vector.js";

/**
 * Abstract base class representing commercial facilities and their components
 */
export abstract class CommercialFacility extends Facility {
    /**
     * Sector of the facility (is commercial!!)
     */
    protected static readonly _FACILITY_SECTOR = FacilitySector.COMMERCIAL;

    /**
     * Base tax revenue generated by the facility
     */
    protected static readonly _BASE_TAX_REVENUE : number;

    /**
     * Base maintenance cost of the facility
     */
    protected static readonly _BASE_MAINTENANCE_COST : number;

    /**
     * Radius used to detect nearby residential facilities
     */
    protected static readonly _RESIDENTIAL_FACILITY_RADIUS : number = 6;

    /**
     * YO CHAT THIS AINT DONE REMEMBER TO DO THIS BEFORE HANDING IT IN WOULD SUCK TO SEE THIS ON THE GIT how do I like bookmark
     * BFS to determine existence and distance to nearby residential facilities
     * @param origin The origin point from which to begin BFS
     * @returns The exact distance the nearest residence is.
     */
    public facilityCheck(origin : Vector2) : { residenceWithinSixUnits : boolean, residenceFound : boolean, distanceToNearestResidence : number } {
        let residenceWithinSixUnits : boolean;
        let residenceFound : boolean;
        let distanceToNearestResidence : number = -1;

        //If residential facility is not found within game bounds mark none found
        //Else, check if the residence is within 6 units
        if (!this.GAME.MAP.BFS(origin,this.GAME.MAP.width + this.GAME.MAP.height,(coordinates : Vector2) : boolean => {
            const CELL = this.GAME.MAP.getCell(coordinates);
                return CELL.facilitySector == FacilitySector.RESIDENTIAL
            })
        ) {
            residenceFound = false;
            residenceWithinSixUnits = false;
        }
        else {
            residenceFound = true;
            //If not within rad of 6
            if (!this.GAME.MAP.BFS(origin,CommercialFacility._RESIDENTIAL_FACILITY_RADIUS,(coordinates : Vector2, distance) : boolean => {
                const CELL = this.GAME.MAP.getCell(coordinates);
                if (CELL.facilitySector == FacilitySector.RESIDENTIAL) {
                    distanceToNearestResidence = distance as number;
                    return true;
                }
                return false;
            })
            ) {
                residenceWithinSixUnits = false;
            } else {
                residenceWithinSixUnits = true;
            }
        }
        return {
            residenceWithinSixUnits, residenceFound, distanceToNearestResidence
        };
    }

    /**
     * CHAT THIS AINT DONE EITHER, DO THIS BEFORE SUBMITTING, THE COMMENTS I MEAN
     * Called every tick, checks monthly logic for revenue and maintenance based on proximity to residences
     * Adjusts game money accordingly
     */
    public override tick(): void {
        if (this.GAME.monthEnded()) {
            let residenceFound : boolean = this.facilityCheck(Vector2.I_UNIT).residenceFound;
            let residenceWithinSixUnits : boolean = this.facilityCheck(Vector2.I_UNIT).residenceWithinSixUnits;
            let radiustoNearestResident : number = this.facilityCheck(Vector2.I_UNIT).distanceToNearestResidence;

            this._age++;

            //Oh this is just tax revenue btw
            if (!residenceFound) {
                this._taxRevenue = 0;
                this._maintenanceCost = 0;
            }
            //FARTHER ffs than r>6
            else if(!residenceWithinSixUnits) {
                this._taxRevenue = 6/radiustoNearestResident * CommercialFacility._BASE_TAX_REVENUE;
                this._maintenanceCost = 6/radiustoNearestResident * CommercialFacility._BASE_MAINTENANCE_COST;
            }
            else {
                this._taxRevenue = CommercialFacility._BASE_TAX_REVENUE;
                this._maintenanceCost = CommercialFacility._BASE_MAINTENANCE_COST;
            }
            this.GAME.money += this._taxRevenue
            this.GAME.money -= this._maintenanceCost;
        }
    }
}


/**
 * Represents a Store facility, a specific type of commercial facility
 * Defines build cost, maintenance, pollution, tax revenue, and static metadata
 */
export class Store extends CommercialFacility {
    /**
     * The facility's type (it's store ofc)
     */
    protected static readonly _FACILITY_TYPE = FacilityType.STORE;

    /**
     * The name of the facility, really.
     */
    protected static readonly _NAME = "Store";

    /**
     * The cost to build the store
     */
    protected static readonly _BUILD_COST: number = 2000000;

    /**
     * The current maintenance cost of the store
     */
    protected _maintenanceCost : number = 50000;

    /**
     * The power consumption of the store
     */
    protected static readonly _POWER_COST: number = 5;

    /**
     * The pollution generated by the store
     */
    protected _pollution : number = 500;	

    /**
     * The tax revenue generated by the store
     */
    protected _taxRevenue : number = 200000;

    /**
     * The base tax revenue for the store
     */
    protected static readonly _BASE_TAX_REVENUE : number = 200000;

    /**
     * The base maintenance cost for the store
     */
    protected static readonly _BASE_MAINTENANCE_COST : number = 50000;
}

/**
 * Represents a Restaurant facility and its respective components
 */
export class Restaurant extends CommercialFacility {
    /**
     * The facility type
     */
    protected static readonly _FACILITY_TYPE = FacilityType.RESTAURANT;

    /**
     * The name of the facility
     */
    protected static readonly _NAME = "Restaurant";

    /**
     * The cost to build the restaurant
     */
    protected static readonly _BUILD_COST: number = 250000;

    /**
     * The maintenance cost of the restaurant
     */
    protected _maintenanceCost : number = 5000;

    /**
     * The power consumption of the restaurant
     */
    protected static readonly _POWER_COST: number = 5;

    /**
     * The pollution generated by the restaurant
     */
    protected _pollution : number = 300;	

    /**
     * The tax revenue produced by the restaurant
     */
    protected _taxRevenue : number = 10000;

    /**
     * The base tax revenue generated by the restaurant
     */
    protected static readonly _BASE_TAX_REVENUE : number = 10000;

    /**
     * The base maintenance cost for the restaurant
     */
    protected static readonly _BASE_MAINTENANCE_COST : number = 5000;
}

/**
 * Represents an Office facility and its respective components
 */
export class Office extends CommercialFacility {
    /**
     * The specific facility type 
     */
    protected static readonly _FACILITY_TYPE = FacilityType.OFFICE;

    /**
     * The name of the facility
     */
    protected static readonly _NAME = "Office";
    
    /**
     * The cost to build the office
     */
    protected static readonly _BUILD_COST: number = 3000000;

    /**
     * The current maintenance cost
     */
    protected _maintenanceCost : number = 5000;

    /**
     * The power consumption of the office
     */
    protected static readonly _POWER_COST: number = 15;

    /**
     * The pollution generated by the office
     */
    protected _pollution : number = 800;	

    /**
     * The tax revenue produced by the office
     */
    protected _taxRevenue : number = 20000;
    
    /**
     * The base tax revenue for the office
     */
    protected static readonly _BASE_TAX_REVENUE : number = 20000;

    /**
     * The base maintenance cost for the office
     */
    protected static readonly _BASE_MAINTENANCE_COST : number = 5000;
}