import { Facility, FacilitySector, FacilityType } from "../facility.js";
import { Canvas } from "../../app/canvas.js";
import { Game } from "../../app/game.js";

/**
 * Represents a Defense Facility and its components
 */
export class DefenseFacility extends Facility {
    /**
     * The facility's sector (it's totally defense)
     */
    protected static readonly _FACILITY_SECTOR = FacilitySector.DEFENSE;

    /**
     * Type of the facility
     */
    protected static readonly _FACILITY_TYPE = FacilityType.DEFENSE;

    /**
     * Name of the facility
     */
    protected static readonly _NAME = "Planetary Defense System";

    /**
     * Cost to build the defense facility
     */
    protected static readonly _BUILD_COST = 1000000000000;

    /**
     * Current maintenance cost
     */
    protected _maintenanceCost: number = 0;

    /**
     * Pollution generated by the facility
     */
    protected _pollution: number = 0;

    /**
     * Tax revenue generated by the facility
     */
    protected _taxRevenue: number = 0;
}

