import { Vector2 } from "../../data_structures/vector.js";
import { Cell } from "../../map/cell.js";
import { Facility, FacilitySector, FacilityType } from "../facility.js";
import { Game } from "../../app/game.js";
import { GameMap } from "../../map/map.js";

/**
 * Abstract base class to be used as a base by industrial facilities
 */
export abstract class IndustrialFacility extends Facility {
    protected static readonly _FACILITY_SECTOR = FacilitySector.INDUSTRIAL;
}

/**
 * Represents a Factory's maintenance, tax revenue, and checks for nearby warehouses that will double its revenue
 */
export class Factory extends IndustrialFacility {
    /**
     * The specific facility type
     */
    protected static readonly _FACILITY_TYPE = FacilityType.FACTORY;

    /**
     * The name of the facility
     */
    protected static readonly _NAME: string = "Factory";

    /**
     * The cost to build the factory
     */
    protected static readonly _BUILD_COST: number = 50000000;

    /**
     * The maximum maintenance cost
     */
    private _maxMaintenanceCost: number = 500000;

    /**
     * The current maintenance cost
     */
    protected _maintenanceCost : number = 0;

    /**
     * The factory's power consumption
     */
    protected static readonly _POWER_COST: number = 50;

    /**
     * The pollution generated by the factory
     */
    protected _pollution: number = 20000;

    /**
     * The current tax revenue
     */
    protected _taxRevenue: number = 0;

    /**
     * The maximum tax revenue for the factory
     */
    private _maxTaxRevenue : number = 5000000;

    /**
     * The base maximum tax revenue before modifiers
     */
    private static readonly _BASE_MAX_TAX_REVENUE : number = 5000000;

    /**
     * The radius used to check for nearby warehouses
     */
    private static readonly _WAREHOUSE_CHECK_RADIUS : number = 5;

    /**
     * The growth rate applied to tax revenue and maintenance cost
     */
    private static readonly _GROWTH_RATE: number = 0.2;

    /**
     * Called every game tick to update state if a month has ended
     */
    public override tick(): void {
        if (this.GAME.monthEnded()) {
            this.updateMaintenanceCost();
            this.updateTaxRevenue();
            this.checkForWarehouse(Vector2.I_UNIT);
            this._age++;
            if (this._taxRevenue >= this._maxTaxRevenue) {
                this.GAME.money += this._maxTaxRevenue;
            }
            else {
                this.GAME.money += this._taxRevenue;
            }

            if (this._maintenanceCost >= this._maxMaintenanceCost) {
                this.GAME.money -= this._maxMaintenanceCost;
            }
            else {
                this.GAME.money -= this._maintenanceCost;
            }
        }
    }

    /**
     * Increases maintenance cost based on age and growth rate
     */
    private updateMaintenanceCost(): void {
        this._maintenanceCost += this._maxMaintenanceCost * (Factory._GROWTH_RATE * this._age);
    }

    /**
     * Increases tax revenue based on age and growth rate
     */
    private updateTaxRevenue() : void {
        this._taxRevenue += this._maxTaxRevenue * (Factory._GROWTH_RATE * this._age);
    }

    /**
     * Checks for a warehouse within a defined radius
     * If found, doubles the max tax revenue and updates it
     * @param origin The starting point for the BFS search
     * @returns Whether a warehouse was found
     */
    private checkForWarehouse(origin : Vector2) : boolean {
        if (this.GAME.MAP.BFS(origin, Factory._WAREHOUSE_CHECK_RADIUS, (coordinates : Vector2) : boolean => {
            const CELL = this.GAME.MAP.getCell(coordinates);
            return CELL.facilitySector == FacilitySector.RESIDENTIAL
        })) {
            this._maxTaxRevenue *= 2;
            this.updateTaxRevenue();
            return true;
        }
        else {
            this._maxTaxRevenue = Factory._BASE_MAX_TAX_REVENUE;
            this.updateTaxRevenue();
            return false;
        }
    }
}

/**
 * Represents a Warehouse, a type of industrial facility
 * Provides support functionality to nearby factories
 */
export class Warehouse extends IndustrialFacility {
    /**
     * The facility type
     */
    protected static readonly _FACILITY_TYPE = FacilityType.WAREHOUSE;

    /**
     * The name of the facility
     */
    protected static readonly _NAME = "Warehouse";

    /**
     * The current maintenance cost 
     */
    protected _maintenanceCost: number = 500000;

    /**
     * The pollution generated
     */
    protected _pollution: number = 0;   

    /**
     * The current tax revenue generated 
     */
    protected _taxRevenue: number = 0;

    /**
     * The amount of power the warehouse consumes
     */
    protected _POWER_COST: number = 10;
}

export class EnvironmentalFacility extends IndustrialFacility {
    protected static readonly _FACILITY_TYPE = FacilityType.ENVIRONMENT;
    protected static readonly _NAME = "Environmental Facility";

    protected static readonly _BUILD_COST: number = 200000000;
    protected _taxRevenue: number = 0;
    protected _maintenanceCost: number = 3000000;
    protected static readonly _POWER_COST: number = 75;
    private static readonly _MAX_POLLUTION_REDUCTION: number = 30000;
    private static readonly _POLLUTION_REDUCTION_RADIUS: number = 10;

    protected _pollution: number = 0;

    // TODO
    public reducePollution(coordinates: Vector2): void {
        //God save the queen (not), and maybe Joe Biden from prostate cancer too. He didn't save the pope tho wtf man?
        // im keeping this comment LMAOOO
        let pollutionReductionAvailable: number = EnvironmentalFacility.MAX_POLLUTION_REDUCTION;

        this.GAME.MAP.BFS(
            coordinates,
            this.GAME.MAP.width + this.GAME.MAP.height,
            (coords: Vector2): boolean => {
                const CELL: Cell = this.GAME.MAP.getCell(coords);
                const POLLUTION: number = CELL.pollution;

                if (pollutionReductionAvailable > POLLUTION) {
                    pollutionReductionAvailable -= POLLUTION;
                    CELL.pollution = 0;
                } else {
                    CELL.pollution -= pollutionReductionAvailable;
                    return true;
                }

                return false;
            }
        )
    }

    public override tick(): void {
        if (this.GAME.monthEnded()) {
            super.tick();
            //Again, all this is handleded later when I give a fuck
            this.reducePollution(Vector2.I_UNIT)
        }
    }

    public static get MAX_POLLUTION_REDUCTION(): number {
        return this._MAX_POLLUTION_REDUCTION;
    }
}

